import React, { useState } from 'react';
import { useStore } from '../../contexts/StoreContext';
import { FileText, Search, Download, ShieldCheck, Check, Copy } from 'lucide-react';

export function Contracts() {
  const { beats, sales } = useStore();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedBeatId, setSelectedBeatId] = useState<string>(beats[0]?.id || 'NR-1001');
  const [copied, setCopied] = useState(false);

  const targetBeat = beats.find(b => b.id === selectedBeatId) || beats[0];

  const standardContractText = targetBeat ? `
NIGHTRUNNA MUSIC LICENSE & LEASE AGREEMENT
==================================================
Beat ID: ${targetBeat.id}
Beat Title: ${targetBeat.title}
Producer Credit: ${targetBeat.metadata?.producer || 'NightRunna'}
BPM: ${targetBeat.metadata?.bpm || '140'} | Key: ${targetBeat.metadata?.key || 'C Minor'}

LICENSING TERMS & PERMISSIONS:
1. Audio Delivery: High Quality Untagged Audio Files
2. Distribution Limit: 100,000 Audio Streams
3. Music Video Limit: 1 Monetized Video
4. Broadcasting Rights: Radio / Live Performance Allowed
5. Copyright Ownership: Producer retains master ownership unless Exclusive License is executed.

Notice: This is an automated license agreement generated by NightRunna Studio.
==================================================
` : 'Select a beat to view generated license agreement.';

  const handleCopy = () => {
    navigator.clipboard.writeText(standardContractText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-zinc-100 flex items-center gap-2">
            Contracts & License Agreements
            <span className="text-xs bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 px-2.5 py-0.5 rounded-full font-mono">
              {sales.length} Executed
            </span>
          </h2>
          <p className="text-sm text-zinc-400">View and generate automated license agreements tied to Beat IDs.</p>
        </div>

        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500" />
          <input 
            type="text" 
            placeholder="Search contracts or Beat ID..." 
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            className="pl-9 pr-4 py-2 bg-zinc-900 border border-zinc-800 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500 w-64"
          />
        </div>
      </div>

      {/* Contract Generator / Viewer */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Beat Selector */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 space-y-4">
          <h3 className="font-bold text-white text-base">Select Beat ID</h3>
          <p className="text-xs text-zinc-400">Choose a beat from your catalog to view or copy its generated legal license agreement.</p>

          <div className="space-y-2 max-h-80 overflow-y-auto">
            {beats.length === 0 ? (
              <p className="text-xs text-zinc-500 italic">No beats uploaded yet.</p>
            ) : (
              beats.map(b => (
                <div 
                  key={b.id}
                  onClick={() => setSelectedBeatId(b.id)}
                  className={`p-3 rounded-lg border text-sm cursor-pointer transition-colors ${
                    selectedBeatId === b.id ? 'bg-indigo-600/20 border-indigo-500 text-white' : 'bg-zinc-950 border-zinc-800 text-zinc-400 hover:text-white'
                  }`}
                >
                  <p className="font-bold">{b.title}</p>
                  <p className="text-xs font-mono text-indigo-400">{b.id} • ${b.price || '39.99'}</p>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Contract Preview Document */}
        <div className="lg:col-span-2 bg-zinc-900 border border-zinc-800 rounded-xl p-6 space-y-4 shadow-xl">
          <div className="flex justify-between items-center pb-3 border-b border-zinc-800">
            <div>
              <h3 className="font-bold text-white text-base">License Preview: {targetBeat?.title || 'Catalog Item'}</h3>
              <p className="text-xs text-indigo-400 font-mono">Beat ID: {targetBeat?.id || 'NR-1001'}</p>
            </div>
            <button 
              onClick={handleCopy}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition-colors flex items-center gap-2"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied Contract' : 'Copy License Text'}
            </button>
          </div>

          <pre className="bg-zinc-950 p-4 rounded-lg border border-zinc-800/80 text-xs text-zinc-300 font-mono overflow-x-auto leading-relaxed whitespace-pre-wrap">
            {standardContractText}
          </pre>
        </div>
      </div>
    </div>
  );
}
